/* Generated By:JJTree&JavaCC: Do not edit this line. regExpGrammarConstants.java */
package regExParsePkg;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface regExpGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int CHOICE = 7;
  /** RegularExpression Id. */
  int STAR = 8;
  /** RegularExpression Id. */
  int CONCAT = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int OPENPAR = 11;
  /** RegularExpression Id. */
  int CLOSEPAR = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int CONSTANT = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"+\"",
    "\"|\"",
    "\"*\"",
    "\",\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "<CONSTANT>",
  };

}
