/* Generated By:JavaCC: Do not edit this line. regExpGrammarTreeConstants.java Version 5.0 */
package regExParsePkg;

public interface regExpGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTCONCAT = 2;
  public int JJTCHOICE = 3;
  public int JJTTERM = 4;
  public int JJTALIAS = 5;
  public int JJTNOT = 6;
  public int JJTELEMENT = 7;


  public String[] jjtNodeName = {
    "START",
    "void",
    "CONCAT",
    "CHOICE",
    "TERM",
    "ALIAS",
    "NOT",
    "ELEMENT",
  };
}
/* JavaCC - OriginalChecksum=3575b94b2f676eb3ab183e00bebd4277 (do not edit this line) */
