/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 5.0 */
package com.umflint.edu.regExParsePkg.test;

public interface eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTADDITIVEEXPRESSION = 2;
  public int JJTMULTIPLICATIVEEXPRESSION = 3;
  public int JJTUNARYEXPRESSION = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTINTEGER = 6;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=363f89f5aaf8e511fff0eb1484ff2213 (do not edit this line) */
