/* Generated By:JavaCC: Do not edit this line. regExpGrammar2TreeConstants.java Version 5.0 */
package regExParsePkg2;

public interface regExpGrammar2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTNEGCONCAT = 2;
  public int JJTCONCAT = 3;
  public int JJTCHOICE = 4;
  public int JJTTERM = 5;
  public int JJTALIAS = 6;
  public int JJTELEMENT = 7;


  public String[] jjtNodeName = {
    "START",
    "void",
    "NEGCONCAT",
    "CONCAT",
    "CHOICE",
    "TERM",
    "ALIAS",
    "ELEMENT",
  };
}
/* JavaCC - OriginalChecksum=e6f5d2ed15bf7459e17624db83912c11 (do not edit this line) */
