/* Generated By:JavaCC: Do not edit this line. queryGrammarConstants.java */
package queryParsePkg;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface queryGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int AS = 8;
  /** RegularExpression Id. */
  int PATTERN = 9;
  /** RegularExpression Id. */
  int WHERE = 10;
  /** RegularExpression Id. */
  int WITHIN = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int CONSTANT = 14;
  /** RegularExpression Id. */
  int EQ = 15;
  /** RegularExpression Id. */
  int NEQ = 16;
  /** RegularExpression Id. */
  int GT = 17;
  /** RegularExpression Id. */
  int LT = 18;
  /** RegularExpression Id. */
  int GEQ = 19;
  /** RegularExpression Id. */
  int LEQ = 20;
  /** RegularExpression Id. */
  int COMMA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"AS\"",
    "\"PATTERN\"",
    "\"WHERE\"",
    "\"WITHIN\"",
    "\"AND\"",
    "<DIGIT>",
    "<CONSTANT>",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\",\"",
  };

}
